### ISSUE TITLE
Updated schema template not updated in action

### ISSUE THREAD

**Issue by NilsWeber98** [sciapp/sampledb#45]
I have an action using a schema template. A change in the schema template is not applied in the action until I edit the action and save it. Is this known or intentional?

If needed, I could provide an example or construct a minimal code to reproduce.

**Comment by FlorianRhiem** [comment]
Thank you for reporting that bug, it should be fixed in [this commit](https://github.com/sciapp/sampledb/commit/52ce7ac33a97bfc78a8758415a39725e56b4b334). A piece of logic for avoiding recursive template updates (e.g. template A includes template B which is updated to include template A) broke template updates. I've added regression tests for the template update actually working.

**Comment by NilsWeber98** [comment]
Yes, it works now. Thank you.
