### ISSUE TITLE
What's the suggested way to add bulk users and add them to a project group?

### ISSUE THREAD

**Issue by link89** [sciapp/sampledb#54]
Hi, I am trying to deploy SampleDB for our lab and now we plan to add a team to start to use it. It looks like I can only add an email address at a time, and I have to wait for the users accept their invitation before I can add them to their project group. I didn't find official API for these in the document, what would be your suggestion to make the above process easier? Thank you.

**Comment by FlorianRhiem** [comment]
Hey @link89, I assume you are not using an LDAP server for authentication? In that case yes, invitation by email is the way to go. If you need to add a large number of users and you want to do this automatically, you could write a small python script, mount it into the container and run it there, to do the email invitations for you. Just be sure to add a short `time.sleep` so that you don't send out tens or hundreds of very similar mails in a very short amount of time.

**Comment by link89** [comment]
>  I assume you are not using an LDAP server for authentication.
No, we have oauth through. I have written a script to invite users.
